dist: xenial
sudo: required
language: c
compiler:
  - clang
  - gcc
env:
  matrix:
    - configure_args=''
    - configure_args='--enable-gcov'
addons:
  apt:
    packages:
      - python-docutils
      - python-sphinx
before_install:
  - git submodule update --init --recursive
  - cd libmaxminddb && ./bootstrap && ./configure && make &&
    sudo make install && cd ..
  - git clone https://github.com/varnishcache/varnish-cache.git
  - cd varnish-cache && ./autogen.sh && ./configure && make &&
    sudo make install && sudo ldconfig && cd ..
  - ./autogen.sh
script:
  - ./configure $configure_args && make CFLAGS="-Wall -Wextra -Werror" VERBOSE=1 distcheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
