language: c
compiler:
  - clang
  - gcc
before_install:
  - git submodule update --init --recursive
  - cd libmaxminddb && ./bootstrap && ./configure && sudo make install && cd ..
  - sudo apt-get update -qq
  - sudo apt-get install -qq apt-transport-https
  - curl -s https://repo.varnish-cache.org/ubuntu/GPG-key.txt |
    sudo apt-key add -
  - echo "deb https://repo.varnish-cache.org/ubuntu/ precise varnish-4.0" |
    sudo tee /etc/apt/sources.list.d/varnish-cache.list
  - sudo apt-get update -qq
  - sudo apt-get install varnish libvarnishapi-dev python-docutils
  - ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra -Werror" && make check
