dist: xenial
sudo: required
language: c
compiler:
  - clang
  - gcc
env:
  - VER=41
  - VER=60lts
addons:
  apt:
    packages:
      - python-docutils
      - python-sphinx
before_install:
  - git submodule update --init --recursive
  - cd libmaxminddb && ./bootstrap && ./configure && make &&
    sudo make install && cd ..
  - curl -s https://packagecloud.io/install/repositories/varnishcache/varnish${VER}/script.deb.sh |
    sudo bash
  - sudo apt-get install varnish-dev
  - ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra -Werror" VERBOSE=1 distcheck
