dist: trusty
sudo: required
language: c
compiler:
  - clang
  - gcc
env:
  - VER=4.1
  - VER=5.0
  - VER=5.1
before_install:
  - git submodule update --init --recursive
  - cd libmaxminddb && ./bootstrap && ./configure && make &&
    sudo make install && cd ..
  - curl -s https://packagecloud.io/install/repositories/varnishcache/varnish${VER/./}/script.deb.sh | sudo bash
  - sudo apt-get install python-docutils
  - sudo apt-get install varnish=${VER}.* varnish-dev=${VER}.*
  - ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra -Werror" VERBOSE=1 distcheck
notifications:
  webhooks:
    urls:
      secure: "BAp2OPYN1sgflZ/c/kDUhhwlEX3I4WvaX2RmorvfPSVUjC5eLEB09Biv1CVyX2GZacECwZL4F8v6YI+i+HU3sPuOLfZxjQLqMp7mlHqZyIRuzhYR3P/mNw789s2dTposRci+0uqJHDSGkurAuAXR5B2R9NK+wkEIUgcqJpGrRn8="
